### ISSUE TITLE
Can not sign in after using this bat 

### ISSUE THREAD

**Issue by Devon-zz** [fly8888/cursor_machine_id#12]
Can not sign in after using this bat

**Comment by Devon-zz** [comment]
![image](https://github.com/user-attachments/assets/efbbd25e-291d-4d10-b959-baf24cf23ca8)
After running the .bat file, when I click "Sign in" on the webpage, there is no response.

**Comment by fly8888** [comment]
Maybe you need to reinstall the cursor. Because it was tested correctly on my device.
