### ISSUE TITLE
mac用python脚本方式修改，重启cusor还是没用

### ISSUE THREAD

**Issue by xingquanGu** [fly8888/cursor_machine_id#24]
要重启电脑吗？

**Comment by fly8888** [comment]
不用重启电脑。只需要重启cursor即可啊。

**Comment by xingquanGu** [comment]
> 不用重启电脑。只需要重启cursor即可啊。

我的cursor是最新版本，这个会不会导致方法失效？

**Comment by xingquanGu** [comment]
> 不用重启电脑。只需要重启cursor即可啊。

目前重启cursor后还是没效果☹️

**Comment by LeonG7** [comment]
> > 不用重启电脑。只需要重启cursor即可啊。
> 
> 目前重启cursor后还是没效果☹️

刚刚亲测有效

**Comment by itliujia** [comment]
@fly8888 还是不行呀，大佬，win10系统
![微信截图_20241225172419](https://github.com/user-attachments/assets/38471d09-9597-4787-a497-b91a8d153943)
![微信截图_20241225172445](https://github.com/user-attachments/assets/de14685d-1011-4b4e-92c2-5a44b18b9447)

**Comment by itliujia** [comment]
手动修改了 machineId就行了
