### ISSUE TITLE
为什么win10执行py文件后，重启cursor会卸载掉了？

### ISSUE THREAD

**Issue by rockking00** [fly8888/cursor_machine_id#25]
win10执行py文件后，重启cursor会卸载掉...

**Comment by fly8888** [comment]
还会被卸载？试试别的方式吧

**Comment by netcore-jroger** [comment]
@rockking00 你是不是更新 cursor 最新版本了？
@fly8888 可以更新到 cursor 最新版本使用吗？

**Comment by fly8888** [comment]
没有试过呢，不确定。

**Comment by fly8888** [comment]
> win10执行py文件后，重启cursor会卸载掉...
不行就手动改下那个文件试试。

**Comment by netcore-jroger** [comment]
@fly8888 大佬试过升级 Cursor 最新版吗？

**Comment by fly8888** [comment]
<img width="218" alt="image" src="https://github.com/user-attachments/assets/6c03f744-05a3-4d8f-8e39-0c5ddbe99616" />
也没提示让升级啊
