### ISSUE TITLE
兄弟，mac 0.44.9版本用不了了

### ISSUE THREAD

**Issue by heguanglei452** [fly8888/cursor_machine_id#27]
退出cursor，在安装脚本，打开依然是无法使用的状态。
求更新....

**Comment by fly8888** [comment]
多重复2次看看呢

**Comment by heguanglei452** [comment]
> 多重复2次看看呢

从昨天到今天，我重复了八九次，仍然不行。
这和我cursor登录的账号额度已经消耗完有关系吗？

![2](https://github.com/user-attachments/assets/1cb22e71-a895-4cd1-98b4-a1d33b1ee730)
![WX20241231-102855@2x](https://github.com/user-attachments/assets/3db4bb1d-5bab-4795-8405-c4aebe6970ba)
![3](https://github.com/user-attachments/assets/bc8eee74-e0b3-4fce-baa1-a6e53e61130f)

**Comment by fly8888** [comment]
.........................这个脚本只解决设备因切换账号过多导致的锁定设备。你这是账号的额度用完了，肯定用不了。把账号删了，重新注册。

**Comment by heguanglei452** [comment]
> .........................这个脚本只解决设备因切换账号过多导致的锁定设备。你这是账号的额度用完了，肯定用不了。把账号删了，重新注册。

谢谢，之前理解错了
